
x-app: &app
  image: crystalbank:dev
  depends_on:
    - database
  env_file:
    - .env-dev
  volumes:
    - ./app:/app

services:
  cmd:
    <<: *app
    deploy:
      replicas: 0
    entrypoint: /bin/bash
    command: -c

  console:
    <<: *app
    entrypoint: /bin/bash
    command: ""
    ports:
      - 4000:3000
    stdin_open: true
    tty: true

  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      target: service
    env_file:
      - .env-dev
    restart: always
    ports:
      - 4010:5432
    volumes:
      - ./storage/postgres:/var/lib/postgresql

  redoc:
    image: redocly/redoc:v2.5.1
    restart: always
    ports:
      - 4002:80
    environment:
      - SPEC_URL=openapi/openapi.json
    volumes:
      - ./app/openapi.json:/usr/share/nginx/html/openapi/openapi.json
      
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /oas/openapi.json
    ports:
      - 4003:8080
    volumes:
      - ./app/openapi.json:/oas/openapi.json

  frontend:
    image: node:22-alpine
    working_dir: /app/frontend
    volumes:
      - ./app:/app
    entrypoint: sh
    command: -c ""
    deploy:
      replicas: 0