
x-app: &app
  image: crystalbank:dev
  depends_on:
    - database
  env_file:
    - .env-dev
  volumes:
    - ./app:/app
    - openapi:/openapi

services:
  cmd:
    <<: *app
    deploy:
      replicas: 0
    entrypoint: /bin/bash
    command: -c

  console:
    <<: *app
    entrypoint: /bin/bash
    command: ""
    ports:
      - 4000:3000
    stdin_open: true
    tty: true

  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      target: service
    env_file:
      - .env-dev
    restart: always
    ports:
      - 4010:5432
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data

  redoc:
    image: redocly/redoc
    restart: always
    ports:
      - 4002:80
    environment:
      - SPEC_URL=openapi/openapi.yml
    volumes:
      - openapi:/usr/share/nginx/html/openapi/

volumes:
  openapi:



