#
# BASE artifact
#
# FROM --platform=linux/amd64 ubuntu:22.04 AS base
FROM 84codes/crystal:1.16.2-ubuntu-24.04 AS base


#
# BUILDER artifact
#
FROM base AS builder

RUN mkdir -p /app
WORKDIR /app
COPY app/shard* /app/

RUN shards install

COPY app/ /app

#
# SERVICE 
#
FROM builder AS service

ENV image_name=crystalbank

WORKDIR /app

EXPOSE 3000
