
x-app: &app
  platform: linux/amd64
  image: crystalbank:dev
  depends_on:
    - database
  env_file:
    - .env-test

services:
  cmd:
    <<: *app
    deploy:
      replicas: 0
    entrypoint: /bin/bash
    command: -c

  database:
    image: postgres:17
    env_file:
      - .env-test
    restart: always
