module CrystalBank::Types::Accounts
  enum ClosureReason
    BY_CUSTOMER
    INACTIVITY
    FRAUD
    SUSPICIOUS_ACTIVITY
    AML_VIOLATION
    KYC_FAILURE
    NEGATIVE_BALANCE
    REPEATED_OVERDRAFT
    TERMS_VIOLATION
    COURT_ORDER
    DEATH_OF_ACCOUNT_HOLDER
    DUPLICATE_ACCOUNT
    PRODUCT_DISCONTINUED
    REGULATORY_REQUIREMENT
    SANCTIONS_MATCH
    BANKRUPTCY
    MINOR_REACHED_AGE_LIMIT
    BUSINESS_DISSOLUTION
    FAILED_REACTIVATION
    BANK_DECISION

    def to_s
      super.to_s.downcase
    end
  end
end
